name: publishing

# This workflow is triggered manually. It creates a production build off of main branch
# and publishes it to GitHub pages https://ardc-fair-checklist.github.io/ardc-fair-checklist

on:
  workflow_dispatch:

jobs:

  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Create production build
        shell: bash
        run: |

          echo "set abort on errors"
          set -e

          echo "get the dependencies"
          npm install

          echo "build"
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'ghactions[bot]'
          user_email: 'ghactions[bot]@users.noreply.github.com'
          commit_message: ':robot: Update github.io page'
