name: testing


on:
  pull_request:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:

  publish:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install the package and its dependencies
        shell: bash
        run: npm ci

      - name: Run the tests
        shell: bash
        run: npm run test
